'use client'

export { Backstory } from './Backstory'
export { Feature } from './Feature'
export { FeatureBoxed } from './FeatureBoxed'
export { Grid } from './Grid'
export { Related } from './Related'
export { Reviews } from './Reviews'
export { Specs } from './Specs'
export { Swipeable } from './Swipeable'
export { Upsells } from './Upsells'
