// Do not edit this file: autogenerated by graphql-code-generator
import * as Types from '../../generated/types';

import { PageLinkFragment } from '../PageLink/PageLink.gql';
export type UspsQueryFragment = { usps?: Types.Maybe<{ uspsMultiple: Array<(
      Pick<Types.PageLink, 'id'>
      & PageLinkFragment
    )> }> };
