// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

import {
  TestEntityUrlDeeperFragment,
  TestEntityUrlDeeperFragmentDoc,
} from './TestEntityUrlDeeper.gql'

export const TestEntityUrlFragmentDoc: DocumentNode<TestEntityUrlFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'TestEntityUrl' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'EntityUrl' } },
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'FragmentSpread',
            name: { kind: 'Name', value: 'TestEntityUrlDeeper' },
            directives: [],
          },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'redirectCode' },
            arguments: [],
            directives: [],
          },
        ],
      },
    },
    ...TestEntityUrlDeeperFragmentDoc.definitions,
  ],
}
export type TestEntityUrlFragment = Pick<Types.EntityUrl, 'redirectCode'> &
  TestEntityUrlDeeperFragment
