// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const StoreLocaleFragmentDoc: DocumentNode<StoreLocaleFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'StoreLocale' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'StoreConfig' } },
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'code' }, arguments: [], directives: [] },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'store_name' },
            arguments: [],
            directives: [],
          },
          { kind: 'Field', name: { kind: 'Name', value: 'locale' }, arguments: [], directives: [] },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'base_currency_code' },
            arguments: [],
            directives: [],
          },
        ],
      },
    },
  ],
}
export type StoreLocaleFragment = Pick<
  Types.StoreConfig,
  'code' | 'store_name' | 'locale' | 'base_currency_code'
>
