// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const StoreConfigDocument: DocumentNode<StoreConfigQuery, StoreConfigQueryVariables> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: { kind: 'Name', value: 'StoreConfig' },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'storeConfig' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'store_code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'store_name' } },
                { kind: 'Field', name: { kind: 'Name', value: 'locale' } },
                { kind: 'Field', name: { kind: 'Name', value: 'base_currency_code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'default_display_currency_code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'title_suffix' } },
                { kind: 'Field', name: { kind: 'Name', value: 'title_prefix' } },
                { kind: 'Field', name: { kind: 'Name', value: 'title_separator' } },
                { kind: 'Field', name: { kind: 'Name', value: 'default_title' } },
                { kind: 'Field', name: { kind: 'Name', value: 'cms_home_page' } },
                { kind: 'Field', name: { kind: 'Name', value: 'catalog_default_sort_by' } },
                { kind: 'Field', name: { kind: 'Name', value: 'category_url_suffix' } },
                { kind: 'Field', name: { kind: 'Name', value: 'product_url_suffix' } },
                { kind: 'Field', name: { kind: 'Name', value: 'base_link_url' } },
                { kind: 'Field', name: { kind: 'Name', value: 'secure_base_link_url' } },
                { kind: 'Field', name: { kind: 'Name', value: 'root_category_uid' } },
                { kind: 'Field', name: { kind: 'Name', value: 'weight_unit' } },
              ],
            },
          },
        ],
      },
    },
  ],
}
export type StoreConfigQueryVariables = Types.Exact<{ [key: string]: never }>

export type StoreConfigQuery = {
  storeConfig?: Types.Maybe<
    Pick<
      Types.StoreConfig,
      | 'store_code'
      | 'store_name'
      | 'locale'
      | 'base_currency_code'
      | 'default_display_currency_code'
      | 'title_suffix'
      | 'title_prefix'
      | 'title_separator'
      | 'default_title'
      | 'cms_home_page'
      | 'catalog_default_sort_by'
      | 'category_url_suffix'
      | 'product_url_suffix'
      | 'base_link_url'
      | 'secure_base_link_url'
      | 'root_category_uid'
      | 'weight_unit'
    >
  >
}
