// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '../../generated/types'

export const ProductFeatureMediaBoxedFragmentDoc: DocumentNode<
  ProductFeatureMediaBoxedFragment,
  unknown
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductFeatureMediaBoxed' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'ProductInterface' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'media_gallery' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                { kind: 'Field', name: { kind: 'Name', value: '__typename' } },
                {
                  kind: 'InlineFragment',
                  typeCondition: {
                    kind: 'NamedType',
                    name: { kind: 'Name', value: 'ProductImage' },
                  },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [{ kind: 'Field', name: { kind: 'Name', value: 'url' } }],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
}
export type ProductFeatureMediaBoxed_VirtualProduct_Fragment = {
  media_gallery?: Types.Maybe<
    Array<
      Types.Maybe<
        | ({ __typename: 'ProductImage' } & Pick<Types.ProductImage, 'url' | 'label'>)
        | ({ __typename: 'ProductVideo' } & Pick<Types.ProductVideo, 'label'>)
      >
    >
  >
}

export type ProductFeatureMediaBoxed_SimpleProduct_Fragment = {
  media_gallery?: Types.Maybe<
    Array<
      Types.Maybe<
        | ({ __typename: 'ProductImage' } & Pick<Types.ProductImage, 'url' | 'label'>)
        | ({ __typename: 'ProductVideo' } & Pick<Types.ProductVideo, 'label'>)
      >
    >
  >
}

export type ProductFeatureMediaBoxed_DownloadableProduct_Fragment = {
  media_gallery?: Types.Maybe<
    Array<
      Types.Maybe<
        | ({ __typename: 'ProductImage' } & Pick<Types.ProductImage, 'url' | 'label'>)
        | ({ __typename: 'ProductVideo' } & Pick<Types.ProductVideo, 'label'>)
      >
    >
  >
}

export type ProductFeatureMediaBoxed_BundleProduct_Fragment = {
  media_gallery?: Types.Maybe<
    Array<
      Types.Maybe<
        | ({ __typename: 'ProductImage' } & Pick<Types.ProductImage, 'url' | 'label'>)
        | ({ __typename: 'ProductVideo' } & Pick<Types.ProductVideo, 'label'>)
      >
    >
  >
}

export type ProductFeatureMediaBoxed_GroupedProduct_Fragment = {
  media_gallery?: Types.Maybe<
    Array<
      Types.Maybe<
        | ({ __typename: 'ProductImage' } & Pick<Types.ProductImage, 'url' | 'label'>)
        | ({ __typename: 'ProductVideo' } & Pick<Types.ProductVideo, 'label'>)
      >
    >
  >
}

export type ProductFeatureMediaBoxed_ConfigurableProduct_Fragment = {
  media_gallery?: Types.Maybe<
    Array<
      Types.Maybe<
        | ({ __typename: 'ProductImage' } & Pick<Types.ProductImage, 'url' | 'label'>)
        | ({ __typename: 'ProductVideo' } & Pick<Types.ProductVideo, 'label'>)
      >
    >
  >
}

export type ProductFeatureMediaBoxedFragment =
  | ProductFeatureMediaBoxed_VirtualProduct_Fragment
  | ProductFeatureMediaBoxed_SimpleProduct_Fragment
  | ProductFeatureMediaBoxed_DownloadableProduct_Fragment
  | ProductFeatureMediaBoxed_BundleProduct_Fragment
  | ProductFeatureMediaBoxed_GroupedProduct_Fragment
  | ProductFeatureMediaBoxed_ConfigurableProduct_Fragment
