// Do not edit this file: autogenerated by graphql-code-generator

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'
import {
  ProductListItemBundleFragment,
  ProductListItemBundleFragmentDoc,
} from '../../magento-product-bundle/ProductListItemBundle.gql'

import {
  ProductListItemConfigurableFragment,
  ProductListItemConfigurableFragmentDoc,
} from '../../magento-product-configurable/ProductListItemConfigurable.gql'

import {
  ProductListItemDownloadableFragment,
  ProductListItemDownloadableFragmentDoc,
} from '../../magento-product-downloadable/ProductListItemDownloadable.gql'

import {
  ProductListItemGroupedFragment,
  ProductListItemGroupedFragmentDoc,
} from '../../magento-product-grouped/ProductListItemGrouped.gql'

import {
  ProductListItemSimpleFragment,
  ProductListItemSimpleFragmentDoc,
} from '../../magento-product-simple/ProductListItemSimple.gql'

import {
  ProductListItemVirtualFragment,
  ProductListItemVirtualFragmentDoc,
} from '../../magento-product-virtual/ProductListItemVirtual.gql'
import {
  ProductListItemFragmentDoc,
  ProductListItem_VirtualProduct_Fragment,
  ProductListItem_SimpleProduct_Fragment,
  ProductListItem_DownloadableProduct_Fragment,
  ProductListItem_BundleProduct_Fragment,
  ProductListItem_GroupedProduct_Fragment,
  ProductListItem_ConfigurableProduct_Fragment,
} from '../../magento-product/ProductListItem/ProductListItem.gql'

export const ProductListItemRendererFragmentDoc: DocumentNode<
  ProductListItemRendererFragment,
  unknown
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductListItemRenderer' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'ProductInterface' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'id' } },
          { kind: 'Field', name: { kind: 'Name', value: '__typename' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItem' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItemBundle' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItemConfigurable' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItemDownloadable' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItemSimple' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItemVirtual' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductListItemGrouped' } },
        ],
      },
    },
    ...ProductListItemFragmentDoc.definitions,
    ...ProductListItemBundleFragmentDoc.definitions,
    ...ProductListItemConfigurableFragmentDoc.definitions,
    ...ProductListItemDownloadableFragmentDoc.definitions,
    ...ProductListItemSimpleFragmentDoc.definitions,
    ...ProductListItemVirtualFragmentDoc.definitions,
    ...ProductListItemGroupedFragmentDoc.definitions,
  ],
}
export type ProductListItemRenderer_VirtualProduct_Fragment = {
  __typename: 'VirtualProduct'
} & Pick<Types.VirtualProduct, 'id'> &
  ProductListItem_VirtualProduct_Fragment &
  ProductListItemVirtualFragment

export type ProductListItemRenderer_SimpleProduct_Fragment = { __typename: 'SimpleProduct' } & Pick<
  Types.SimpleProduct,
  'id'
> &
  ProductListItem_SimpleProduct_Fragment &
  ProductListItemSimpleFragment

export type ProductListItemRenderer_DownloadableProduct_Fragment = {
  __typename: 'DownloadableProduct'
} & Pick<Types.DownloadableProduct, 'id'> &
  ProductListItem_DownloadableProduct_Fragment &
  ProductListItemDownloadableFragment

export type ProductListItemRenderer_BundleProduct_Fragment = { __typename: 'BundleProduct' } & Pick<
  Types.BundleProduct,
  'id'
> &
  ProductListItem_BundleProduct_Fragment &
  ProductListItemBundleFragment

export type ProductListItemRenderer_GroupedProduct_Fragment = {
  __typename: 'GroupedProduct'
} & Pick<Types.GroupedProduct, 'id'> &
  ProductListItem_GroupedProduct_Fragment &
  ProductListItemGroupedFragment

export type ProductListItemRenderer_ConfigurableProduct_Fragment = {
  __typename: 'ConfigurableProduct'
} & Pick<Types.ConfigurableProduct, 'id'> &
  ProductListItem_ConfigurableProduct_Fragment &
  ProductListItemConfigurableFragment

export type ProductListItemRendererFragment =
  | ProductListItemRenderer_VirtualProduct_Fragment
  | ProductListItemRenderer_SimpleProduct_Fragment
  | ProductListItemRenderer_DownloadableProduct_Fragment
  | ProductListItemRenderer_BundleProduct_Fragment
  | ProductListItemRenderer_GroupedProduct_Fragment
  | ProductListItemRenderer_ConfigurableProduct_Fragment
