sources:
  - name: m2
    handler:
      graphql:
        endpoint: '{graphCommerce.magentoEndpoint}'
        useGETForQueries: true
        batch: false
        operationHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
          X-ReCaptcha: "{context.headers['x-recaptcha']}"
          Preview-Version: "{context.headers['preview-version']}"
          Content-Currency: "{context.headers['content-currency']}"
          X-Magento-Cache-Id: "{context.headers['x-magento-cache-id']}"
          X-Forwarded-For: "{context.headers['x-forwarded-for']}"
serve:
  playground: true
plugins:
  - '@graphcommerce/graphql-mesh/plugin/forward-headers':
      forwardHeaders:
        - X-Magento-Cache-Id
