// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const BraintreeClientTokenDocument: DocumentNode<
  BraintreeClientTokenMutation,
  BraintreeClientTokenMutationVariables
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'mutation',
      name: { kind: 'Name', value: 'BraintreeClientToken' },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'createBraintreeClientToken' } },
        ],
      },
    },
  ],
}
export type BraintreeClientTokenMutationVariables = Types.Exact<{ [key: string]: never }>

export type BraintreeClientTokenMutation = Pick<Types.Mutation, 'createBraintreeClientToken'>
