// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const OrderDetailPageDocument: DocumentNode<
  OrderDetailPageQuery,
  OrderDetailPageQueryVariables
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: { kind: 'Name', value: 'OrderDetailPage' },
      variableDefinitions: [
        {
          kind: 'VariableDefinition',
          variable: { kind: 'Variable', name: { kind: 'Name', value: 'orderNumber' } },
          type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } },
        },
      ],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'customer' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'orders' },
                  arguments: [
                    {
                      kind: 'Argument',
                      name: { kind: 'Name', value: 'filter' },
                      value: {
                        kind: 'ObjectValue',
                        fields: [
                          {
                            kind: 'ObjectField',
                            name: { kind: 'Name', value: 'number' },
                            value: {
                              kind: 'ObjectValue',
                              fields: [
                                {
                                  kind: 'ObjectField',
                                  name: { kind: 'Name', value: 'eq' },
                                  value: {
                                    kind: 'Variable',
                                    name: { kind: 'Name', value: 'orderNumber' },
                                  },
                                },
                              ],
                            },
                          },
                        ],
                      },
                    },
                  ],
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'items' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'number' } },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'shipments' },
                              selectionSet: {
                                kind: 'SelectionSet',
                                selections: [
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'tracking' },
                                    selectionSet: {
                                      kind: 'SelectionSet',
                                      selections: [
                                        { kind: 'Field', name: { kind: 'Name', value: 'carrier' } },
                                        { kind: 'Field', name: { kind: 'Name', value: 'number' } },
                                        { kind: 'Field', name: { kind: 'Name', value: 'title' } },
                                      ],
                                    },
                                  },
                                ],
                              },
                            },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'total' },
                              selectionSet: {
                                kind: 'SelectionSet',
                                selections: [
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'grand_total' },
                                    selectionSet: {
                                      kind: 'SelectionSet',
                                      selections: [
                                        {
                                          kind: 'Field',
                                          name: { kind: 'Name', value: 'currency' },
                                        },
                                        { kind: 'Field', name: { kind: 'Name', value: 'value' } },
                                      ],
                                    },
                                  },
                                ],
                              },
                            },
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'items' },
                              selectionSet: {
                                kind: 'SelectionSet',
                                selections: [
                                  { kind: 'Field', name: { kind: 'Name', value: 'product_sku' } },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'product_url_key' },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'quantity_ordered' },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'quantity_shipped' },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'quantity_canceled' },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'quantity_invoiced' },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'quantity_refunded' },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'quantity_returned' },
                                  },
                                  { kind: 'Field', name: { kind: 'Name', value: 'product_name' } },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'selected_options' },
                                    selectionSet: {
                                      kind: 'SelectionSet',
                                      selections: [
                                        { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                                        { kind: 'Field', name: { kind: 'Name', value: 'value' } },
                                      ],
                                    },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'discounts' },
                                    selectionSet: {
                                      kind: 'SelectionSet',
                                      selections: [
                                        {
                                          kind: 'Field',
                                          name: { kind: 'Name', value: 'amount' },
                                          selectionSet: {
                                            kind: 'SelectionSet',
                                            selections: [
                                              {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'currency' },
                                              },
                                              {
                                                kind: 'Field',
                                                name: { kind: 'Name', value: 'value' },
                                              },
                                            ],
                                          },
                                        },
                                        { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                                      ],
                                    },
                                  },
                                  {
                                    kind: 'Field',
                                    name: { kind: 'Name', value: 'product_sale_price' },
                                    selectionSet: {
                                      kind: 'SelectionSet',
                                      selections: [
                                        {
                                          kind: 'Field',
                                          name: { kind: 'Name', value: 'currency' },
                                        },
                                        { kind: 'Field', name: { kind: 'Name', value: 'value' } },
                                      ],
                                    },
                                  },
                                ],
                              },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'order_date' } },
                          ],
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
}
export type OrderDetailPageQueryVariables = Types.Exact<{
  orderNumber?: Types.Maybe<Types.Scalars['String']>
}>

export type OrderDetailPageQuery = {
  customer?: Types.Maybe<{
    orders?: Types.Maybe<{
      items: Array<
        Types.Maybe<
          Pick<Types.CustomerOrder, 'number' | 'order_date'> & {
            shipments?: Types.Maybe<
              Array<
                Types.Maybe<{
                  tracking?: Types.Maybe<
                    Array<Types.Maybe<Pick<Types.ShipmentTracking, 'carrier' | 'number' | 'title'>>>
                  >
                }>
              >
            >
            total?: Types.Maybe<{ grand_total: Pick<Types.Money, 'currency' | 'value'> }>
            items?: Types.Maybe<
              Array<
                Types.Maybe<
                  | (Pick<
                      Types.DownloadableOrderItem,
                      | 'product_sku'
                      | 'product_url_key'
                      | 'quantity_ordered'
                      | 'quantity_shipped'
                      | 'quantity_canceled'
                      | 'quantity_invoiced'
                      | 'quantity_refunded'
                      | 'quantity_returned'
                      | 'product_name'
                    > & {
                      selected_options?: Types.Maybe<
                        Array<Types.Maybe<Pick<Types.OrderItemOption, 'label' | 'value'>>>
                      >
                      discounts?: Types.Maybe<
                        Array<
                          Types.Maybe<
                            Pick<Types.Discount, 'label'> & {
                              amount: Pick<Types.Money, 'currency' | 'value'>
                            }
                          >
                        >
                      >
                      product_sale_price: Pick<Types.Money, 'currency' | 'value'>
                    })
                  | (Pick<
                      Types.BundleOrderItem,
                      | 'product_sku'
                      | 'product_url_key'
                      | 'quantity_ordered'
                      | 'quantity_shipped'
                      | 'quantity_canceled'
                      | 'quantity_invoiced'
                      | 'quantity_refunded'
                      | 'quantity_returned'
                      | 'product_name'
                    > & {
                      selected_options?: Types.Maybe<
                        Array<Types.Maybe<Pick<Types.OrderItemOption, 'label' | 'value'>>>
                      >
                      discounts?: Types.Maybe<
                        Array<
                          Types.Maybe<
                            Pick<Types.Discount, 'label'> & {
                              amount: Pick<Types.Money, 'currency' | 'value'>
                            }
                          >
                        >
                      >
                      product_sale_price: Pick<Types.Money, 'currency' | 'value'>
                    })
                  | (Pick<
                      Types.OrderItem,
                      | 'product_sku'
                      | 'product_url_key'
                      | 'quantity_ordered'
                      | 'quantity_shipped'
                      | 'quantity_canceled'
                      | 'quantity_invoiced'
                      | 'quantity_refunded'
                      | 'quantity_returned'
                      | 'product_name'
                    > & {
                      selected_options?: Types.Maybe<
                        Array<Types.Maybe<Pick<Types.OrderItemOption, 'label' | 'value'>>>
                      >
                      discounts?: Types.Maybe<
                        Array<
                          Types.Maybe<
                            Pick<Types.Discount, 'label'> & {
                              amount: Pick<Types.Money, 'currency' | 'value'>
                            }
                          >
                        >
                      >
                      product_sale_price: Pick<Types.Money, 'currency' | 'value'>
                    })
                >
              >
            >
          }
        >
      >
    }>
  }>
}
