// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '../../generated/types'

import { PageLinkFragment, PageLinkFragmentDoc } from '../PageLink/PageLink.gql'

export const RowContentLinksFragmentDoc: DocumentNode<RowContentLinksFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'RowContentLinks' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RowContentLinks' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'title' } },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'contentLinks' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [{ kind: 'FragmentSpread', name: { kind: 'Name', value: 'PageLink' } }],
            },
          },
        ],
      },
    },
    ...PageLinkFragmentDoc.definitions,
  ],
}
export type RowContentLinksFragment = Pick<Types.RowContentLinks, 'title'> & {
  contentLinks: Array<PageLinkFragment>
}
