// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

import { MoneyFragment, MoneyFragmentDoc } from '../../magento-store/Money.gql'

export const ProductPagePriceFragmentDoc: DocumentNode<ProductPagePriceFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductPagePrice' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'ProductInterface' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'price_range' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'maximum_price' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'regular_price' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'FragmentSpread', name: { kind: 'Name', value: 'Money' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'discount' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'amount_off' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'percent_off' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'final_price' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'FragmentSpread', name: { kind: 'Name', value: 'Money' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'fixed_product_taxes' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'amount' },
                              selectionSet: {
                                kind: 'SelectionSet',
                                selections: [
                                  {
                                    kind: 'FragmentSpread',
                                    name: { kind: 'Name', value: 'Money' },
                                  },
                                ],
                              },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                          ],
                        },
                      },
                    ],
                  },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'minimum_price' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'regular_price' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'FragmentSpread', name: { kind: 'Name', value: 'Money' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'discount' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'amount_off' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'percent_off' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'final_price' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'FragmentSpread', name: { kind: 'Name', value: 'Money' } },
                          ],
                        },
                      },
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'fixed_product_taxes' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            {
                              kind: 'Field',
                              name: { kind: 'Name', value: 'amount' },
                              selectionSet: {
                                kind: 'SelectionSet',
                                selections: [
                                  {
                                    kind: 'FragmentSpread',
                                    name: { kind: 'Name', value: 'Money' },
                                  },
                                ],
                              },
                            },
                            { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                          ],
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'price_tiers' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'discount' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      { kind: 'Field', name: { kind: 'Name', value: 'amount_off' } },
                      { kind: 'Field', name: { kind: 'Name', value: 'percent_off' } },
                    ],
                  },
                },
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'final_price' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'Money' } },
                    ],
                  },
                },
                { kind: 'Field', name: { kind: 'Name', value: 'quantity' } },
              ],
            },
          },
        ],
      },
    },
    ...MoneyFragmentDoc.definitions,
  ],
}
export type ProductPagePrice_VirtualProduct_Fragment = {
  price_range: {
    maximum_price?: Types.Maybe<{
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }>
    minimum_price: {
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }
  }
  price_tiers?: Types.Maybe<
    Array<
      Types.Maybe<
        Pick<Types.TierPrice, 'quantity'> & {
          discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
          final_price?: Types.Maybe<MoneyFragment>
        }
      >
    >
  >
}

export type ProductPagePrice_SimpleProduct_Fragment = {
  price_range: {
    maximum_price?: Types.Maybe<{
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }>
    minimum_price: {
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }
  }
  price_tiers?: Types.Maybe<
    Array<
      Types.Maybe<
        Pick<Types.TierPrice, 'quantity'> & {
          discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
          final_price?: Types.Maybe<MoneyFragment>
        }
      >
    >
  >
}

export type ProductPagePrice_DownloadableProduct_Fragment = {
  price_range: {
    maximum_price?: Types.Maybe<{
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }>
    minimum_price: {
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }
  }
  price_tiers?: Types.Maybe<
    Array<
      Types.Maybe<
        Pick<Types.TierPrice, 'quantity'> & {
          discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
          final_price?: Types.Maybe<MoneyFragment>
        }
      >
    >
  >
}

export type ProductPagePrice_BundleProduct_Fragment = {
  price_range: {
    maximum_price?: Types.Maybe<{
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }>
    minimum_price: {
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }
  }
  price_tiers?: Types.Maybe<
    Array<
      Types.Maybe<
        Pick<Types.TierPrice, 'quantity'> & {
          discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
          final_price?: Types.Maybe<MoneyFragment>
        }
      >
    >
  >
}

export type ProductPagePrice_GroupedProduct_Fragment = {
  price_range: {
    maximum_price?: Types.Maybe<{
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }>
    minimum_price: {
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }
  }
  price_tiers?: Types.Maybe<
    Array<
      Types.Maybe<
        Pick<Types.TierPrice, 'quantity'> & {
          discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
          final_price?: Types.Maybe<MoneyFragment>
        }
      >
    >
  >
}

export type ProductPagePrice_ConfigurableProduct_Fragment = {
  price_range: {
    maximum_price?: Types.Maybe<{
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }>
    minimum_price: {
      regular_price: MoneyFragment
      discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
      final_price: MoneyFragment
      fixed_product_taxes?: Types.Maybe<
        Array<
          Types.Maybe<
            Pick<Types.FixedProductTax, 'label'> & { amount?: Types.Maybe<MoneyFragment> }
          >
        >
      >
    }
  }
  price_tiers?: Types.Maybe<
    Array<
      Types.Maybe<
        Pick<Types.TierPrice, 'quantity'> & {
          discount?: Types.Maybe<Pick<Types.ProductDiscount, 'amount_off' | 'percent_off'>>
          final_price?: Types.Maybe<MoneyFragment>
        }
      >
    >
  >
}

export type ProductPagePriceFragment =
  | ProductPagePrice_VirtualProduct_Fragment
  | ProductPagePrice_SimpleProduct_Fragment
  | ProductPagePrice_DownloadableProduct_Fragment
  | ProductPagePrice_BundleProduct_Fragment
  | ProductPagePrice_GroupedProduct_Fragment
  | ProductPagePrice_ConfigurableProduct_Fragment
