// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const CartItemSimpleFragmentDoc: DocumentNode<CartItemSimpleFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'CartItemSimple' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'SimpleCartItem' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [{ kind: 'Field', name: { kind: 'Name', value: 'id' } }],
      },
    },
  ],
}
export type CartItemSimpleFragment = Pick<Types.SimpleCartItem, 'id'>
