// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const ProductPageSimpleFragmentDoc: DocumentNode<ProductPageSimpleFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductPageSimple' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'SimpleProduct' } },
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'id' }, arguments: [], directives: [] },
        ],
      },
    },
  ],
}
export type ProductPageSimpleFragment = Pick<Types.SimpleProduct, 'id'>
