// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

import {
  ProductPageCustomizable_VirtualProduct_Fragment,
  ProductPageCustomizable_SimpleProduct_Fragment,
  ProductPageCustomizable_DownloadableProduct_Fragment,
  ProductPageCustomizable_BundleProduct_Fragment,
  ProductPageCustomizable_ConfigurableProduct_Fragment,
  ProductPageCustomizableFragmentDoc,
} from '../magento-product/ProductPageCustomizable.gql'
import {
  ProductPageInterface_VirtualProduct_Fragment,
  ProductPageInterface_SimpleProduct_Fragment,
  ProductPageInterface_DownloadableProduct_Fragment,
  ProductPageInterface_BundleProduct_Fragment,
  ProductPageInterface_GroupedProduct_Fragment,
  ProductPageInterface_ConfigurableProduct_Fragment,
  ProductPageInterfaceFragmentDoc,
} from '../magento-product/ProductPageInterface.gql'

export const ProductPageSimpleFragmentDoc: DocumentNode<ProductPageSimpleFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductPageSimple' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'SimpleProduct' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductPageInterface' } },
          { kind: 'FragmentSpread', name: { kind: 'Name', value: 'ProductPageCustomizable' } },
        ],
      },
    },
    ...ProductPageInterfaceFragmentDoc.definitions,
    ...ProductPageCustomizableFragmentDoc.definitions,
  ],
}
export type ProductPageSimpleFragment = ProductPageInterface_SimpleProduct_Fragment &
  ProductPageCustomizable_SimpleProduct_Fragment
