/* hash:4155502298 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-customer/components/Invoice/InvoiceItem */
import { InvoiceItem as InvoiceItemBundleInvoiceItem } from '@graphcommerce/magento-product-bundle/plugins/BundleInvoiceItem'
import { InvoiceItem as InvoiceItemDownloadableInvoiceItem } from '@graphcommerce/magento-product-downloadable/plugins/DownloadableInvoiceItem'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { InvoiceItem as InvoiceItemOriginal } from './InvoiceItem.original'

// Re-export everything from the original file except the intercepted exports
export * from './InvoiceItem.original'

type InvoiceItemBundleInvoiceItemProps = OmitPrev<
  React.ComponentProps<typeof InvoiceItemBundleInvoiceItem>,
  'Prev'
>

const InvoiceItemBundleInvoiceItemInterceptor = (props: InvoiceItemBundleInvoiceItemProps) => (
  <InvoiceItemBundleInvoiceItem {...props} Prev={InvoiceItemOriginal} />
)

type InvoiceItemDownloadableInvoiceItemProps = OmitPrev<
  React.ComponentProps<typeof InvoiceItemDownloadableInvoiceItem>,
  'Prev'
>

const InvoiceItemDownloadableInvoiceItemInterceptor = (
  props: InvoiceItemDownloadableInvoiceItemProps,
) => (
  <InvoiceItemDownloadableInvoiceItem {...props} Prev={InvoiceItemBundleInvoiceItemInterceptor} />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./InvoiceItem.tsx} for original source file
 * @see {InvoiceItemBundleInvoiceItem} for source of applied plugin
 * @see {InvoiceItemDownloadableInvoiceItem} for source of applied plugin
 */
export const InvoiceItem = InvoiceItemDownloadableInvoiceItemInterceptor
