/* hash:1014179215 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-customer/components/CreditMemo/CreditMemoItem */
import { CreditMemoItem as CreditMemoItemBundleCreditMemoItem } from '@graphcommerce/magento-product-bundle/plugins/BundleCreditMemoItem'
import { CreditMemoItem as CreditMemoItemDownloadableCreditMemoItem } from '@graphcommerce/magento-product-downloadable/plugins/DownloadableCreditMemoItem'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { CreditMemoItem as CreditMemoItemOriginal } from './CreditMemoItem.original'

// Re-export everything from the original file except the intercepted exports
export * from './CreditMemoItem.original'

type CreditMemoItemBundleCreditMemoItemProps = OmitPrev<
  React.ComponentProps<typeof CreditMemoItemBundleCreditMemoItem>,
  'Prev'
>

const CreditMemoItemBundleCreditMemoItemInterceptor = (
  props: CreditMemoItemBundleCreditMemoItemProps,
) => <CreditMemoItemBundleCreditMemoItem {...props} Prev={CreditMemoItemOriginal} />

type CreditMemoItemDownloadableCreditMemoItemProps = OmitPrev<
  React.ComponentProps<typeof CreditMemoItemDownloadableCreditMemoItem>,
  'Prev'
>

const CreditMemoItemDownloadableCreditMemoItemInterceptor = (
  props: CreditMemoItemDownloadableCreditMemoItemProps,
) => (
  <CreditMemoItemDownloadableCreditMemoItem
    {...props}
    Prev={CreditMemoItemBundleCreditMemoItemInterceptor}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./CreditMemoItem.tsx} for original source file
 * @see {CreditMemoItemBundleCreditMemoItem} for source of applied plugin
 * @see {CreditMemoItemDownloadableCreditMemoItem} for source of applied plugin
 */
export const CreditMemoItem = CreditMemoItemDownloadableCreditMemoItemInterceptor
