// Do not edit this file: autogenerated by graphql-code-generator
import * as Types from '@reachdigital/magento-graphql';

import { CategoryBreadcrumbFragment } from '../../magento-category/CategoryBreadcrumb.gql';
export type CategorySearchResultFragment = (
  Pick<Types.CategoryTree, 'url_path' | 'name'>
  & CategoryBreadcrumbFragment
);
