// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

import {
  AvailablePaymentMethodFragment,
  AvailablePaymentMethodFragmentDoc,
} from './AvailablePaymentMethod.gql'
import {
  SelectedPaymentMethodFragment,
  SelectedPaymentMethodFragmentDoc,
} from './SelectedPaymentMethod.gql'

export const PaymentMethodContextFragmentDoc: DocumentNode<
  PaymentMethodContextFragment,
  unknown
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'PaymentMethodContext' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Cart' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'available_payment_methods' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'FragmentSpread', name: { kind: 'Name', value: 'AvailablePaymentMethod' } },
              ],
            },
          },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'selected_payment_method' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'FragmentSpread', name: { kind: 'Name', value: 'SelectedPaymentMethod' } },
              ],
            },
          },
        ],
      },
    },
    ...AvailablePaymentMethodFragmentDoc.definitions,
    ...SelectedPaymentMethodFragmentDoc.definitions,
  ],
}
export type PaymentMethodContextFragment = {
  available_payment_methods?: Types.Maybe<Array<Types.Maybe<AvailablePaymentMethodFragment>>>
  selected_payment_method?: Types.Maybe<SelectedPaymentMethodFragment>
}
