// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

import {
  AvailableShippingMethodFragment,
  AvailableShippingMethodFragmentDoc,
} from './AvailableShippingMethod.gql'
import {
  SelectedShippingMethodFragment,
  SelectedShippingMethodFragmentDoc,
} from './SelectedShippingMethod.gql'

export const ShippingCartAddressFragmentDoc: DocumentNode<ShippingCartAddressFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ShippingCartAddress' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'ShippingCartAddress' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'firstname' } },
          { kind: 'Field', name: { kind: 'Name', value: 'lastname' } },
          { kind: 'Field', name: { kind: 'Name', value: 'company' } },
          { kind: 'Field', name: { kind: 'Name', value: 'city' } },
          { kind: 'Field', name: { kind: 'Name', value: 'postcode' } },
          { kind: 'Field', name: { kind: 'Name', value: 'street' } },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'country' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'label' } },
              ],
            },
          },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'region' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                { kind: 'Field', name: { kind: 'Name', value: 'region_id' } },
              ],
            },
          },
          { kind: 'Field', name: { kind: 'Name', value: 'telephone' } },
          { kind: 'Field', name: { kind: 'Name', value: 'customer_notes' } },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'selected_shipping_method' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'FragmentSpread', name: { kind: 'Name', value: 'SelectedShippingMethod' } },
              ],
            },
          },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'available_shipping_methods' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'FragmentSpread',
                  name: { kind: 'Name', value: 'AvailableShippingMethod' },
                },
              ],
            },
          },
        ],
      },
    },
    ...SelectedShippingMethodFragmentDoc.definitions,
    ...AvailableShippingMethodFragmentDoc.definitions,
  ],
}
export type ShippingCartAddressFragment = Pick<
  Types.ShippingCartAddress,
  | 'firstname'
  | 'lastname'
  | 'company'
  | 'city'
  | 'postcode'
  | 'street'
  | 'telephone'
  | 'customer_notes'
> & {
  country: Pick<Types.CartAddressCountry, 'code' | 'label'>
  region?: Types.Maybe<Pick<Types.CartAddressRegion, 'code' | 'label' | 'region_id'>>
  selected_shipping_method?: Types.Maybe<SelectedShippingMethodFragment>
  available_shipping_methods?: Types.Maybe<Array<Types.Maybe<AvailableShippingMethodFragment>>>
}
