/* hash:1885865136 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-customer/hooks/useSignInForm */

import { useSignInForm as useSignInFormuseSignInFormMergeCart } from '@graphcommerce/magento-cart/plugins/useSignInFormMergeCart'
import { useSignInForm as useSignInFormOriginal } from './useSignInForm.original'

// Re-export everything from the original file except the intercepted exports
export * from './useSignInForm.original'

const useSignInFormuseSignInFormMergeCartInterceptor: typeof useSignInFormOriginal = (...args) => {
  return useSignInFormuseSignInFormMergeCart(useSignInFormOriginal, ...args)
}

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./useSignInForm.ts} for original source file
 * @see {useSignInFormuseSignInFormMergeCart} for source of applied plugin
 */
export const useSignInForm = useSignInFormuseSignInFormMergeCartInterceptor
