'use client'

import { CssAndFramerMotionProvider } from '@graphcommerce/next-ui'
import { CssBaseline, ThemeProvider } from '@mui/material'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter'
import type { ReactNode } from 'react'
import { createContext, useContext } from 'react'
import type { LayoutQuery } from '../graphql/Layout.gql'
import { ApolloWrapper } from '../lib/apollo/ApolloWrapper'
import { I18nProvider } from '../lib/i18n/I18nProvider'
import type { GraphCommerceStorefrontConfig } from '../lib/storefront'
import { theme } from './theme'

// Layout Context for passing server-fetched layout data to client components
const LayoutContext = createContext<LayoutQuery | undefined>(undefined)

export function useLayoutData() {
  const ctx = useContext(LayoutContext)
  // Return empty object if context is undefined (during initial render)
  return ctx ?? {}
}

type ProvidersProps = {
  children: ReactNode
  storefront: GraphCommerceStorefrontConfig
  layoutData?: LayoutQuery
}

/**
 * Client-side providers wrapper for the App Router Combines all necessary context providers in one
 * component
 *
 * AppRouterCacheProvider collects CSS generated by MUI on the server and injects it into the head.
 * This prevents FOUC (Flash of Unstyled Content). See:
 * https://mui.com/material-ui/integrations/nextjs/#app-router
 *
 * Note: StorefrontProvider is removed - storefront config should be derived from URL params using
 * useStorefrontConfig() hook or passed as props from RSC
 */
export function Providers({ children, storefront, layoutData }: ProvidersProps) {
  return (
    <AppRouterCacheProvider options={{ enableCssLayer: true }}>
      <CssAndFramerMotionProvider>
        <I18nProvider locale={storefront.linguiLocale ?? storefront.locale}>
          <ApolloWrapper storefront={storefront}>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <LayoutContext.Provider value={layoutData}>{children}</LayoutContext.Provider>
            </ThemeProvider>
          </ApolloWrapper>
        </I18nProvider>
      </CssAndFramerMotionProvider>
    </AppRouterCacheProvider>
  )
}
