// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import {
  ProductListItem_VirtualProduct_Fragment,
  ProductListItem_SimpleProduct_Fragment,
  ProductListItem_DownloadableProduct_Fragment,
  ProductListItem_BundleProduct_Fragment,
  ProductListItem_GroupedProduct_Fragment,
  ProductListItem_ConfigurableProduct_Fragment,
  ProductListItemFragmentDoc,
} from './ProductListItem.gql'

export const ProductPageUpsellFragmentDoc: DocumentNode<ProductPageUpsellFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductPageUpsell' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'ProductInterface' } },
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'upsell_products' },
            arguments: [],
            directives: [],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'FragmentSpread',
                  name: { kind: 'Name', value: 'ProductListItem' },
                  directives: [],
                },
              ],
            },
          },
        ],
      },
    },
    ...ProductListItemFragmentDoc.definitions,
  ],
}
export type ProductPageUpsell_VirtualProduct_Fragment = {
  upsell_products?: Types.Maybe<
    Array<
      Types.Maybe<
        | ProductListItem_VirtualProduct_Fragment
        | ProductListItem_SimpleProduct_Fragment
        | ProductListItem_DownloadableProduct_Fragment
        | ProductListItem_BundleProduct_Fragment
        | ProductListItem_GroupedProduct_Fragment
        | ProductListItem_ConfigurableProduct_Fragment
      >
    >
  >
}

export type ProductPageUpsell_SimpleProduct_Fragment = {
  upsell_products?: Types.Maybe<
    Array<
      Types.Maybe<
        | ProductListItem_VirtualProduct_Fragment
        | ProductListItem_SimpleProduct_Fragment
        | ProductListItem_DownloadableProduct_Fragment
        | ProductListItem_BundleProduct_Fragment
        | ProductListItem_GroupedProduct_Fragment
        | ProductListItem_ConfigurableProduct_Fragment
      >
    >
  >
}

export type ProductPageUpsell_DownloadableProduct_Fragment = {
  upsell_products?: Types.Maybe<
    Array<
      Types.Maybe<
        | ProductListItem_VirtualProduct_Fragment
        | ProductListItem_SimpleProduct_Fragment
        | ProductListItem_DownloadableProduct_Fragment
        | ProductListItem_BundleProduct_Fragment
        | ProductListItem_GroupedProduct_Fragment
        | ProductListItem_ConfigurableProduct_Fragment
      >
    >
  >
}

export type ProductPageUpsell_BundleProduct_Fragment = {
  upsell_products?: Types.Maybe<
    Array<
      Types.Maybe<
        | ProductListItem_VirtualProduct_Fragment
        | ProductListItem_SimpleProduct_Fragment
        | ProductListItem_DownloadableProduct_Fragment
        | ProductListItem_BundleProduct_Fragment
        | ProductListItem_GroupedProduct_Fragment
        | ProductListItem_ConfigurableProduct_Fragment
      >
    >
  >
}

export type ProductPageUpsell_GroupedProduct_Fragment = {
  upsell_products?: Types.Maybe<
    Array<
      Types.Maybe<
        | ProductListItem_VirtualProduct_Fragment
        | ProductListItem_SimpleProduct_Fragment
        | ProductListItem_DownloadableProduct_Fragment
        | ProductListItem_BundleProduct_Fragment
        | ProductListItem_GroupedProduct_Fragment
        | ProductListItem_ConfigurableProduct_Fragment
      >
    >
  >
}

export type ProductPageUpsell_ConfigurableProduct_Fragment = {
  upsell_products?: Types.Maybe<
    Array<
      Types.Maybe<
        | ProductListItem_VirtualProduct_Fragment
        | ProductListItem_SimpleProduct_Fragment
        | ProductListItem_DownloadableProduct_Fragment
        | ProductListItem_BundleProduct_Fragment
        | ProductListItem_GroupedProduct_Fragment
        | ProductListItem_ConfigurableProduct_Fragment
      >
    >
  >
}

export type ProductPageUpsellFragment =
  | ProductPageUpsell_VirtualProduct_Fragment
  | ProductPageUpsell_SimpleProduct_Fragment
  | ProductPageUpsell_DownloadableProduct_Fragment
  | ProductPageUpsell_BundleProduct_Fragment
  | ProductPageUpsell_GroupedProduct_Fragment
  | ProductPageUpsell_ConfigurableProduct_Fragment
