/* hash:2010478868 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-cart/components/CartStartCheckout/CartStartCheckout */
import { CartStartCheckout as CartStartCheckoutGoogleDatalayerCartStartCheckout } from '@graphcommerce/google-datalayer/plugins/GoogleDatalayerCartStartCheckout'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { CartStartCheckout as CartStartCheckoutOriginal } from './CartStartCheckout.original'

// Re-export everything from the original file except the intercepted exports
export * from './CartStartCheckout.original'

type CartStartCheckoutGoogleDatalayerCartStartCheckoutProps = OmitPrev<
  React.ComponentProps<typeof CartStartCheckoutGoogleDatalayerCartStartCheckout>,
  'Prev'
>

const CartStartCheckoutGoogleDatalayerCartStartCheckoutInterceptor = (
  props: CartStartCheckoutGoogleDatalayerCartStartCheckoutProps,
) => (
  <CartStartCheckoutGoogleDatalayerCartStartCheckout {...props} Prev={CartStartCheckoutOriginal} />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./CartStartCheckout.tsx} for original source file
 * @see {CartStartCheckoutGoogleDatalayerCartStartCheckout} for source of applied plugin
 */
export const CartStartCheckout = CartStartCheckoutGoogleDatalayerCartStartCheckoutInterceptor
