export { default as iconArrowBack } from './arrow-left.svg'
export { default as iconArrowForward } from './arrow-right.svg'
export { default as iconShoppingBag } from './bag.svg'
export { default as iconInvoice } from './box-alt.svg'
export { default as iconBox } from './box.svg'
export { default as iconOrderBefore } from './calendar.svg'
export { default as iconCancelAlt } from './cancel-alt.svg'
export { default as iconCartAdd } from './cart-add.svg'
export { default as iconCart } from './cart.svg'
export { default as iconChat } from './chat-alt.svg'
export { default as iconCustomerService } from './chat.svg'
export { default as iconChevronDown } from './chevron-down.svg'
export { default as iconChevronBack, default as iconChevronLeft } from './chevron-left.svg'
export { default as iconChevronRight } from './chevron-right.svg'
export { default as iconChevronUp } from './chevron-up.svg'
export { default as iconCirle } from './circle.svg'
export { default as iconClose } from './close.svg'
export { default as iconCreditCard, default as iconId } from './credit-card.svg'
export { default as iconEllypsis } from './ellypsis.svg'
export { default as iconEmail, default as iconEmailOutline } from './envelope-alt.svg'
export { default as icon404 } from './explore.svg'
export { default as iconEyeClosed } from './eye-closed.svg'
export { default as iconEyeCrossed } from './eye-crossed.svg'
export { default as iconEye } from './eye.svg'
export { default as iconHeart } from './favourite.svg'
export { default as iconMenu } from './hamburger.svg'
export { default as iconParty } from './happy-face.svg'
export { default as iconAddresses, default as iconHome } from './home-alt.svg'
export { default as iconLanguage } from './language.svg'
export { default as iconLocation } from './location.svg'
export { default as iconLock } from './lock.svg'
export { default as iconFullscreen } from './maximise.svg'
export { default as iconFullscreenExit } from './minimise.svg'
export { default as iconMin } from './minus.svg'
export { default as iconMoon } from './moon.svg'
export { default as iconNewspaper } from './news.svg'
export { default as iconCheckmark } from './ok.svg'
export { default as iconPerson } from './person-alt.svg'
export { default as iconPlay } from './play.svg'
export { default as iconPlus } from './plus.svg'
export { default as iconShutdown } from './power.svg'
export { default as iconRefresh } from './refresh.svg'
export { default as iconSadFace } from './sad-face.svg'
export { default as iconSearch } from './search.svg'
export { default as iconPhone } from './smartphone.svg'
export { default as iconStar } from './star.svg'
export { default as iconSun } from './sun.svg'
