/* hash:2076339385 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/graphql/components/GraphQLProvider/GraphQLProvider */
import { GraphQLProvider as GraphQLProviderGrecaptchaGraphQLProvider } from '@graphcommerce/googlerecaptcha/plugins/GrecaptchaGraphQLProvider'
import { GraphQLProvider as GraphQLProviderMagentoCartGraphqlProvider } from '@graphcommerce/magento-cart/plugins/MagentoCartGraphqlProvider'
import { GraphQLProvider as GraphQLProviderAddCompareTypePolicies } from '@graphcommerce/magento-compare/plugins/AddCompareTypePolicies'
import { GraphQLProvider as GraphQLProviderMagentoCustomerGraphqlProvider } from '@graphcommerce/magento-customer/plugins/MagentoCustomerGraphqlProvider'
import { GraphQLProvider as GraphQLProviderXMagentoCacheIdGraphQLProvider } from '@graphcommerce/magento-customer/plugins/XMagentoCacheIdGraphQLProvider'
import { GraphQLProvider as GraphQLProviderAddRecentlyViewedProductsTypePolicies } from '@graphcommerce/magento-recently-viewed-products/plugins/AddRecentlyViewedProductsTypePolicies'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { GraphQLProvider as GraphQLProviderOriginal } from './GraphQLProvider.original'

// Re-export everything from the original file except the intercepted exports
export * from './GraphQLProvider.original'

type GraphQLProviderMagentoCustomerGraphqlProviderProps = OmitPrev<
  React.ComponentProps<typeof GraphQLProviderMagentoCustomerGraphqlProvider>,
  'Prev'
>

const GraphQLProviderMagentoCustomerGraphqlProviderInterceptor = (
  props: GraphQLProviderMagentoCustomerGraphqlProviderProps,
) => <GraphQLProviderMagentoCustomerGraphqlProvider {...props} Prev={GraphQLProviderOriginal} />

type GraphQLProviderXMagentoCacheIdGraphQLProviderProps = OmitPrev<
  React.ComponentProps<typeof GraphQLProviderXMagentoCacheIdGraphQLProvider>,
  'Prev'
> &
  GraphQLProviderMagentoCustomerGraphqlProviderProps

const GraphQLProviderXMagentoCacheIdGraphQLProviderInterceptor = (
  props: GraphQLProviderXMagentoCacheIdGraphQLProviderProps,
) => (
  <GraphQLProviderXMagentoCacheIdGraphQLProvider
    {...props}
    Prev={GraphQLProviderMagentoCustomerGraphqlProviderInterceptor}
  />
)

type GraphQLProviderMagentoCartGraphqlProviderProps = OmitPrev<
  React.ComponentProps<typeof GraphQLProviderMagentoCartGraphqlProvider>,
  'Prev'
> &
  GraphQLProviderXMagentoCacheIdGraphQLProviderProps

const GraphQLProviderMagentoCartGraphqlProviderInterceptor = (
  props: GraphQLProviderMagentoCartGraphqlProviderProps,
) => (
  <GraphQLProviderMagentoCartGraphqlProvider
    {...props}
    Prev={GraphQLProviderXMagentoCacheIdGraphQLProviderInterceptor}
  />
)

type GraphQLProviderGrecaptchaGraphQLProviderProps = OmitPrev<
  React.ComponentProps<typeof GraphQLProviderGrecaptchaGraphQLProvider>,
  'Prev'
> &
  GraphQLProviderMagentoCartGraphqlProviderProps

const GraphQLProviderGrecaptchaGraphQLProviderInterceptor = (
  props: GraphQLProviderGrecaptchaGraphQLProviderProps,
) => (
  <GraphQLProviderGrecaptchaGraphQLProvider
    {...props}
    Prev={GraphQLProviderMagentoCartGraphqlProviderInterceptor}
  />
)

type GraphQLProviderAddCompareTypePoliciesProps = OmitPrev<
  React.ComponentProps<typeof GraphQLProviderAddCompareTypePolicies>,
  'Prev'
> &
  GraphQLProviderGrecaptchaGraphQLProviderProps

const GraphQLProviderAddCompareTypePoliciesInterceptor = (
  props: GraphQLProviderAddCompareTypePoliciesProps,
) => (
  <GraphQLProviderAddCompareTypePolicies
    {...props}
    Prev={GraphQLProviderGrecaptchaGraphQLProviderInterceptor}
  />
)

type GraphQLProviderAddRecentlyViewedProductsTypePoliciesProps = OmitPrev<
  React.ComponentProps<typeof GraphQLProviderAddRecentlyViewedProductsTypePolicies>,
  'Prev'
> &
  GraphQLProviderAddCompareTypePoliciesProps

const GraphQLProviderAddRecentlyViewedProductsTypePoliciesInterceptor = (
  props: GraphQLProviderAddRecentlyViewedProductsTypePoliciesProps,
) => (
  <GraphQLProviderAddRecentlyViewedProductsTypePolicies
    {...props}
    Prev={GraphQLProviderAddCompareTypePoliciesInterceptor}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./GraphQLProvider.original.tsx} for original source file
 * @see {GraphQLProviderMagentoCustomerGraphqlProvider} for source of applied plugin
 * @see {GraphQLProviderXMagentoCacheIdGraphQLProvider} for source of applied plugin
 * @see {GraphQLProviderMagentoCartGraphqlProvider} for source of applied plugin
 * @see {GraphQLProviderGrecaptchaGraphQLProvider} for source of applied plugin
 * @see {GraphQLProviderAddCompareTypePolicies} for source of applied plugin
 * @see {GraphQLProviderAddRecentlyViewedProductsTypePolicies} for source of applied plugin
 */
export const GraphQLProvider =
  GraphQLProviderAddRecentlyViewedProductsTypePoliciesInterceptor as typeof GraphQLProviderOriginal &
    React.FC<GraphQLProviderAddRecentlyViewedProductsTypePoliciesProps>
