/* hash:2099018247 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-product/components/ProductListItems/ProductListItemsBase */
import { ProductListItemsBase as ProductListItemsBaseGoogleDatalayerProductListItemsBase } from '@graphcommerce/google-datalayer/plugins/GoogleDatalayerProductListItemsBase'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { ProductListItemsBase as ProductListItemsBaseOriginal } from './ProductListItemsBase.original'

// Re-export everything from the original file except the intercepted exports
export * from './ProductListItemsBase.original'

type ProductListItemsBaseGoogleDatalayerProductListItemsBaseProps = OmitPrev<
  React.ComponentProps<typeof ProductListItemsBaseGoogleDatalayerProductListItemsBase>,
  'Prev'
>

const ProductListItemsBaseGoogleDatalayerProductListItemsBaseInterceptor = (
  props: ProductListItemsBaseGoogleDatalayerProductListItemsBaseProps,
) => (
  <ProductListItemsBaseGoogleDatalayerProductListItemsBase
    {...props}
    Prev={ProductListItemsBaseOriginal}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./ProductListItemsBase.tsx} for original source file
 * @see {ProductListItemsBaseGoogleDatalayerProductListItemsBase} for source of applied plugin
 */
export const ProductListItemsBase =
  ProductListItemsBaseGoogleDatalayerProductListItemsBaseInterceptor
