// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '../../generated/types'

export const RowSwipeableGridFragmentDoc: DocumentNode<RowSwipeableGridFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'RowSwipeableGrid' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RowSwipeableGrid' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [{ kind: 'Field', name: { kind: 'Name', value: 'title' } }],
      },
    },
  ],
}
export type RowSwipeableGridFragment = Pick<Types.RowSwipeableGrid, 'title'>
