/* hash:575673576 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/graphql-mesh/meshConfig */

import { meshConfig as meshConfigmeshRecaptcha } from '@graphcommerce/googlerecaptcha/plugins/meshRecaptcha'
import { meshConfig as meshConfigmeshConfigFake } from '@graphcommerce/graphql-mesh/plugins/meshConfigFake'
import { meshConfig as meshConfigmeshConfigM2Rest } from '@graphcommerce/magento-graphql-rest/plugins/meshConfigM2Rest'
import { meshConfig as meshConfigmagentoOrderItemMesh } from '@graphcommerce/magento-graphql/plugins/magentoOrderItemMesh'
import { meshConfig as meshConfigmagentoOrders } from '@graphcommerce/magento-graphql/plugins/magentoOrders'
import { meshConfig as meshConfigmeshConfigAttrValue } from '@graphcommerce/magento-graphql/plugins/meshConfigAttrValue'
import { meshConfig as meshConfigmeshMagentoStore } from '@graphcommerce/magento-store/plugins/meshMagentoStore'
import { meshConfig as meshConfigOriginal } from './meshConfig.original'

// Re-export everything from the original file except the intercepted exports
export * from './meshConfig.original'

const meshConfigmeshConfigFakeInterceptor: typeof meshConfigOriginal = (...args) => {
  return meshConfigmeshConfigFake(meshConfigOriginal, ...args)
}
const meshConfigmagentoOrderItemMeshInterceptor: typeof meshConfigmeshConfigFakeInterceptor = (
  ...args
) => {
  return meshConfigmagentoOrderItemMesh(meshConfigmeshConfigFakeInterceptor, ...args)
}
const meshConfigmagentoOrdersInterceptor: typeof meshConfigmagentoOrderItemMeshInterceptor = (
  ...args
) => {
  return meshConfigmagentoOrders(meshConfigmagentoOrderItemMeshInterceptor, ...args)
}
const meshConfigmeshConfigAttrValueInterceptor: typeof meshConfigmagentoOrdersInterceptor = (
  ...args
) => {
  return meshConfigmeshConfigAttrValue(meshConfigmagentoOrdersInterceptor, ...args)
}
const meshConfigmeshMagentoStoreInterceptor: typeof meshConfigmeshConfigAttrValueInterceptor = (
  ...args
) => {
  return meshConfigmeshMagentoStore(meshConfigmeshConfigAttrValueInterceptor, ...args)
}
const meshConfigmeshRecaptchaInterceptor: typeof meshConfigmeshMagentoStoreInterceptor = (
  ...args
) => {
  return meshConfigmeshRecaptcha(meshConfigmeshMagentoStoreInterceptor, ...args)
}
const meshConfigmeshConfigM2RestInterceptor: typeof meshConfigmeshRecaptchaInterceptor = (
  ...args
) => {
  return meshConfigmeshConfigM2Rest(meshConfigmeshRecaptchaInterceptor, ...args)
}

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./meshConfig.ts} for original source file
 * @see {meshConfigmeshConfigFake} for source of applied plugin
 * @see {meshConfigmagentoOrderItemMesh} for source of applied plugin
 * @see {meshConfigmagentoOrders} for source of applied plugin
 * @see {meshConfigmeshConfigAttrValue} for source of applied plugin
 * @see {meshConfigmeshMagentoStore} for source of applied plugin
 * @see {meshConfigmeshRecaptcha} for source of applied plugin
 * @see {meshConfigmeshConfigM2Rest} for source of applied plugin
 */
export const meshConfig = meshConfigmeshConfigM2RestInterceptor
