// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const OrderCardItemImagesDocument: DocumentNode<
  OrderCardItemImagesQuery,
  OrderCardItemImagesQueryVariables
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'OperationDefinition',
      operation: 'query',
      name: { kind: 'Name', value: 'OrderCardItemImages' },
      variableDefinitions: [
        {
          kind: 'VariableDefinition',
          variable: { kind: 'Variable', name: { kind: 'Name', value: 'urlKeys' } },
          type: {
            kind: 'NonNullType',
            type: {
              kind: 'ListType',
              type: {
                kind: 'NonNullType',
                type: { kind: 'NamedType', name: { kind: 'Name', value: 'String' } },
              },
            },
          },
        },
      ],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'products' },
            arguments: [
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'filter' },
                value: {
                  kind: 'ObjectValue',
                  fields: [
                    {
                      kind: 'ObjectField',
                      name: { kind: 'Name', value: 'url_key' },
                      value: {
                        kind: 'ObjectValue',
                        fields: [
                          {
                            kind: 'ObjectField',
                            name: { kind: 'Name', value: 'in' },
                            value: { kind: 'Variable', name: { kind: 'Name', value: 'urlKeys' } },
                          },
                        ],
                      },
                    },
                  ],
                },
              },
            ],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'items' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'Field',
                        name: { kind: 'Name', value: 'thumbnail' },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [
                            { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                            { kind: 'Field', name: { kind: 'Name', value: 'url' } },
                          ],
                        },
                      },
                      { kind: 'Field', name: { kind: 'Name', value: 'url_key' } },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
}
export type OrderCardItemImagesQueryVariables = Types.Exact<{
  urlKeys: Array<Types.Scalars['String']> | Types.Scalars['String']
}>

export type OrderCardItemImagesQuery = {
  products?: Types.Maybe<{
    items?: Types.Maybe<
      Array<
        Types.Maybe<
          | (Pick<Types.VirtualProduct, 'url_key'> & {
              thumbnail?: Types.Maybe<Pick<Types.ProductImage, 'label' | 'url'>>
            })
          | (Pick<Types.SimpleProduct, 'url_key'> & {
              thumbnail?: Types.Maybe<Pick<Types.ProductImage, 'label' | 'url'>>
            })
          | (Pick<Types.DownloadableProduct, 'url_key'> & {
              thumbnail?: Types.Maybe<Pick<Types.ProductImage, 'label' | 'url'>>
            })
          | (Pick<Types.BundleProduct, 'url_key'> & {
              thumbnail?: Types.Maybe<Pick<Types.ProductImage, 'label' | 'url'>>
            })
          | (Pick<Types.GroupedProduct, 'url_key'> & {
              thumbnail?: Types.Maybe<Pick<Types.ProductImage, 'label' | 'url'>>
            })
          | (Pick<Types.ConfigurableProduct, 'url_key'> & {
              thumbnail?: Types.Maybe<Pick<Types.ProductImage, 'label' | 'url'>>
            })
        >
      >
    >
  }>
}
