// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

import { CmsPageContentFragment, CmsPageContentFragmentDoc } from './CmsPageContent.gql'
import { CmsPageMetaFragment, CmsPageMetaFragmentDoc } from './CmsPageMeta.gql'

export const CmsPageQueryFragmentDoc: DocumentNode<CmsPageQueryFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'CmsPageQueryFragment' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Query' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'cmsPage' },
            arguments: [
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'identifier' },
                value: { kind: 'Variable', name: { kind: 'Name', value: 'urlKey' } },
              },
            ],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'identifier' } },
                { kind: 'FragmentSpread', name: { kind: 'Name', value: 'CmsPageMeta' } },
                { kind: 'FragmentSpread', name: { kind: 'Name', value: 'CmsPageContent' } },
              ],
            },
          },
        ],
      },
    },
    ...CmsPageMetaFragmentDoc.definitions,
    ...CmsPageContentFragmentDoc.definitions,
  ],
}
export type CmsPageQueryFragment = {
  cmsPage?: Types.Maybe<
    Pick<Types.CmsPage, 'identifier'> & CmsPageMetaFragment & CmsPageContentFragment
  >
}
