// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const CmsPageContentFragmentDoc: DocumentNode<CmsPageContentFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'CmsPageContent' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'CmsPage' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: 'content_heading' } },
          { kind: 'Field', name: { kind: 'Name', value: 'content' } },
        ],
      },
    },
  ],
}
export type CmsPageContentFragment = Pick<Types.CmsPage, 'content_heading' | 'content'>
