// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '../../generated/types'

export const RowProductSpecsFragmentDoc: DocumentNode<RowProductSpecsFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'RowProductSpecs' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'RowProductSpecs' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [{ kind: 'Field', name: { kind: 'Name', value: 'identity' } }],
      },
    },
  ],
}
export type RowProductSpecsFragment = Pick<Types.RowProductSpecs, 'identity'>
