sources:
  - name: graphcms
    handler:
      graphql:
        useGETForQueries: true
        endpoint: ${GRAPHCMS_URL}
        retry: 3
        operationHeaders:
          gcms-locales: "{context.headers['gcms-locales']}"
    transforms:
      - filterSchema:
          mode: 'bare'
          filters:
            # - '*.!{documentInStages*,createdAt*,updatedAt*,publishedAt*,history,scheduledIn*,AND,OR,NOT}'
            - '*.!{localizations,scheduledIn,documentInStages,createdAt,updatedAt,publishedAt,createdBy,updatedBy,publishedBy,history}'
            - 'Query.*.!{locales}'
            # - 'Query.!{node,*Multiple*,*Version,asset*,scheduled*,user*}'
            # - 'Query.!{row*,pageLink*,footers*,banner*}'
            # - 'Asset.{id,alt,url,width,height,mimeType,size}'
            # - 'Asset.url.!transformation'
            - 'Mutation.!*'
            # - '*.!row*'
            # - '*.*.!{after,before,last,forceParentLocale,locales}'
            # - '*.!{_search,id,id_*,identity,identity_*,uspsMultiple_*,pages,pages_*,author*,date*,metaDescription*,metaTitle*}'
      - prune:
          skipPruning: []
  - name: m2
    handler:
      graphql:
        endpoint: ${MAGENTO_ENDPOINT}
        useGETForQueries: true
        schemaHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
        operationHeaders:
          Store: '{context.headers.store}'
          Authorization: '{context.headers.authorization}'
          X-ReCaptcha: "{context.headers['x-recaptcha']}"
          Preview-Version: "{context.headers['preview-version']}"
          Content-Currency: "{context.headers['content-currency']}"
serve:
  playground: true
