// Do not edit this file: autogenerated by graphql-code-generator

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '../../generated/types'
import { RowColumnOneFragment, RowColumnOneFragmentDoc } from '../RowColumnOne/RowColumnOne.gql'

import {
  RowColumnThreeFragment,
  RowColumnThreeFragmentDoc,
} from '../RowColumnThree/RowColumnThree.gql'

import { RowColumnTwoFragment, RowColumnTwoFragmentDoc } from '../RowColumnTwo/RowColumnTwo.gql'
import {
  RowContentLinksFragment,
  RowContentLinksFragmentDoc,
} from '../RowContentLinks/RowContentLinks.gql'

import {
  RowProductFeatureFragment,
  RowProductFeatureFragmentDoc,
} from '../RowProductFeature/RowProductFeature.gql'

import {
  RowProductFeatureBoxedFragment,
  RowProductFeatureBoxedFragmentDoc,
} from '../RowProductFeatureBoxed/RowProductFeatureBoxed.gql'

import {
  RowProductRelatedFragment,
  RowProductRelatedFragmentDoc,
} from '../RowProductRelated/RowProductRelated.gql'

import {
  RowProductReviewsFragment,
  RowProductReviewsFragmentDoc,
} from '../RowProductReviews/RowProductReviews.gql'
import {
  RowProductSpecsFragment,
  RowProductSpecsFragmentDoc,
} from '../RowProductSpecs/RowProductSpecs.gql'

import {
  RowProductUpsellsFragment,
  RowProductUpsellsFragmentDoc,
} from '../RowProductUpsells/RowProductUpsells.gql'
import { RowQuoteFragment, RowQuoteFragmentDoc } from '../RowQuote/RowQuote.gql'

import {
  RowSpecialBannerFragment,
  RowSpecialBannerFragmentDoc,
} from '../RowSpecialBanner/RowSpecialBanner.gql'

export const ProductpagesContentQueryFragmentDoc: DocumentNode<
  ProductpagesContentQueryFragment,
  unknown
> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'ProductpagesContentQueryFragment' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Query' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'productpages' },
            arguments: [
              {
                kind: 'Argument',
                name: { kind: 'Name', value: 'where' },
                value: {
                  kind: 'ObjectValue',
                  fields: [
                    {
                      kind: 'ObjectField',
                      name: { kind: 'Name', value: 'url_in' },
                      value: { kind: 'Variable', name: { kind: 'Name', value: 'productUrls' } },
                    },
                  ],
                },
              },
            ],
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                {
                  kind: 'Field',
                  name: { kind: 'Name', value: 'content' },
                  selectionSet: {
                    kind: 'SelectionSet',
                    selections: [
                      {
                        kind: 'InlineFragment',
                        typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'Node' } },
                        selectionSet: {
                          kind: 'SelectionSet',
                          selections: [{ kind: 'Field', name: { kind: 'Name', value: 'id' } }],
                        },
                      },
                      { kind: 'Field', name: { kind: 'Name', value: '__typename' } },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowColumnOne' } },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowColumnTwo' } },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowColumnThree' } },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowSpecialBanner' } },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowContentLinks' } },
                      {
                        kind: 'FragmentSpread',
                        name: { kind: 'Name', value: 'RowProductFeature' },
                      },
                      {
                        kind: 'FragmentSpread',
                        name: { kind: 'Name', value: 'RowProductFeatureBoxed' },
                      },
                      {
                        kind: 'FragmentSpread',
                        name: { kind: 'Name', value: 'RowProductReviews' },
                      },
                      {
                        kind: 'FragmentSpread',
                        name: { kind: 'Name', value: 'RowProductRelated' },
                      },
                      {
                        kind: 'FragmentSpread',
                        name: { kind: 'Name', value: 'RowProductUpsells' },
                      },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowProductSpecs' } },
                      { kind: 'FragmentSpread', name: { kind: 'Name', value: 'RowQuote' } },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
    ...RowColumnOneFragmentDoc.definitions,
    ...RowColumnTwoFragmentDoc.definitions,
    ...RowColumnThreeFragmentDoc.definitions,
    ...RowSpecialBannerFragmentDoc.definitions,
    ...RowContentLinksFragmentDoc.definitions,
    ...RowProductFeatureFragmentDoc.definitions,
    ...RowProductFeatureBoxedFragmentDoc.definitions,
    ...RowProductReviewsFragmentDoc.definitions,
    ...RowProductRelatedFragmentDoc.definitions,
    ...RowProductUpsellsFragmentDoc.definitions,
    ...RowProductSpecsFragmentDoc.definitions,
    ...RowQuoteFragmentDoc.definitions,
  ],
}
export type ProductpagesContentQueryFragment = {
  productpages: Array<{
    content: Array<
      | ({ __typename: 'RowColumnOne' } & Pick<Types.RowColumnOne, 'id'> & RowColumnOneFragment)
      | ({ __typename: 'RowColumnThree' } & Pick<Types.RowColumnThree, 'id'> &
          RowColumnThreeFragment)
      | ({ __typename: 'RowColumnTwo' } & Pick<Types.RowColumnTwo, 'id'> & RowColumnTwoFragment)
      | ({ __typename: 'RowContentLinks' } & Pick<Types.RowContentLinks, 'id'> &
          RowContentLinksFragment)
      | ({ __typename: 'RowProductFeature' } & Pick<Types.RowProductFeature, 'id'> &
          RowProductFeatureFragment)
      | ({ __typename: 'RowProductFeatureBoxed' } & Pick<Types.RowProductFeatureBoxed, 'id'> &
          RowProductFeatureBoxedFragment)
      | ({ __typename: 'RowProductRelated' } & Pick<Types.RowProductRelated, 'id'> &
          RowProductRelatedFragment)
      | ({ __typename: 'RowProductReviews' } & Pick<Types.RowProductReviews, 'id'> &
          RowProductReviewsFragment)
      | ({ __typename: 'RowProductSpecs' } & Pick<Types.RowProductSpecs, 'id'> &
          RowProductSpecsFragment)
      | ({ __typename: 'RowProductUpsells' } & Pick<Types.RowProductUpsells, 'id'> &
          RowProductUpsellsFragment)
      | ({ __typename: 'RowQuote' } & Pick<Types.RowQuote, 'id'> & RowQuoteFragment)
      | ({ __typename: 'RowSpecialBanner' } & Pick<Types.RowSpecialBanner, 'id'> &
          RowSpecialBannerFragment)
    >
  }>
}
