// Do not edit this file: autogenerated by graphql-code-generator
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import * as Types from '@reachdigital/magento-graphql'

export const CartAddressFragmentDoc: DocumentNode<CartAddressFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'CartAddress' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'CartAddressInterface' } },
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          { kind: 'Field', name: { kind: 'Name', value: '__typename' } },
          { kind: 'Field', name: { kind: 'Name', value: 'firstname' } },
          { kind: 'Field', name: { kind: 'Name', value: 'lastname' } },
          { kind: 'Field', name: { kind: 'Name', value: 'city' } },
          { kind: 'Field', name: { kind: 'Name', value: 'company' } },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'country' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'label' } },
              ],
            },
          },
          { kind: 'Field', name: { kind: 'Name', value: 'postcode' } },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'region' },
            selectionSet: {
              kind: 'SelectionSet',
              selections: [
                { kind: 'Field', name: { kind: 'Name', value: 'code' } },
                { kind: 'Field', name: { kind: 'Name', value: 'label' } },
                { kind: 'Field', name: { kind: 'Name', value: 'region_id' } },
              ],
            },
          },
          { kind: 'Field', name: { kind: 'Name', value: 'street' } },
          { kind: 'Field', name: { kind: 'Name', value: 'telephone' } },
        ],
      },
    },
  ],
}
export type CartAddress_BillingCartAddress_Fragment = { __typename: 'BillingCartAddress' } & Pick<
  Types.BillingCartAddress,
  'firstname' | 'lastname' | 'city' | 'company' | 'postcode' | 'street' | 'telephone'
> & {
    country: Pick<Types.CartAddressCountry, 'code' | 'label'>
    region?: Types.Maybe<Pick<Types.CartAddressRegion, 'code' | 'label' | 'region_id'>>
  }

export type CartAddress_ShippingCartAddress_Fragment = { __typename: 'ShippingCartAddress' } & Pick<
  Types.ShippingCartAddress,
  'firstname' | 'lastname' | 'city' | 'company' | 'postcode' | 'street' | 'telephone'
> & {
    country: Pick<Types.CartAddressCountry, 'code' | 'label'>
    region?: Types.Maybe<Pick<Types.CartAddressRegion, 'code' | 'label' | 'region_id'>>
  }

export type CartAddressFragment =
  | CartAddress_BillingCartAddress_Fragment
  | CartAddress_ShippingCartAddress_Fragment
