# Layout query for navigation menu and footer blocks
query Layout {
  menu: categories {
    items {
      uid
      include_in_menu
      name
      url_path
      level
      is_anchor
      children {
        uid
        include_in_menu
        name
        url_path
        level
        is_anchor
        children {
          uid
          include_in_menu
          name
          url_path
          level
          is_anchor
          children {
            uid
            include_in_menu
            name
            url_path
            level
            is_anchor
          }
        }
      }
    }
  }

  cmsBlocks(identifiers: ["footer_links_block"]) {
    items {
      identifier
      content
    }
  }
}
