// Do not edit this file: autogenerated by graphql-code-generator
import * as Types from '@reachdigital/magento-graphql'

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
export const CategoryDescriptionFragmentDoc: DocumentNode<CategoryDescriptionFragment, unknown> = {
  kind: 'Document',
  definitions: [
    {
      kind: 'FragmentDefinition',
      name: { kind: 'Name', value: 'CategoryDescription' },
      typeCondition: { kind: 'NamedType', name: { kind: 'Name', value: 'CategoryTree' } },
      directives: [],
      selectionSet: {
        kind: 'SelectionSet',
        selections: [
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'description' },
            arguments: [],
            directives: [],
          },
          { kind: 'Field', name: { kind: 'Name', value: 'name' }, arguments: [], directives: [] },
          {
            kind: 'Field',
            name: { kind: 'Name', value: 'display_mode' },
            arguments: [],
            directives: [],
          },
        ],
      },
    },
  ],
}
export type CategoryDescriptionFragment = Pick<
  Types.CategoryTree,
  'description' | 'name' | 'display_mode'
>
