/* hash:1847132242 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-product/components/ProductPageGallery/ProductPageGallery */
import { ProductPageGallery as ProductPageGalleryConfigurableProductPageGallery } from '@graphcommerce/magento-product-configurable/plugins/ConfigurableProductPage/ConfigurableProductPageGallery'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { ProductPageGallery as ProductPageGalleryOriginal } from './ProductPageGallery.original'

// Re-export everything from the original file except the intercepted exports
export * from './ProductPageGallery.original'

type ProductPageGalleryConfigurableProductPageGalleryProps = OmitPrev<
  React.ComponentProps<typeof ProductPageGalleryConfigurableProductPageGallery>,
  'Prev'
>

const ProductPageGalleryConfigurableProductPageGalleryInterceptor = (
  props: ProductPageGalleryConfigurableProductPageGalleryProps,
) => (
  <ProductPageGalleryConfigurableProductPageGallery {...props} Prev={ProductPageGalleryOriginal} />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./ProductPageGallery.tsx} for original source file
 * @see {ProductPageGalleryConfigurableProductPageGallery} for source of applied plugin
 */
export const ProductPageGallery = ProductPageGalleryConfigurableProductPageGalleryInterceptor
