/* hash:718493731 */
/* eslint-disable */
/* This file is automatically generated for @graphcommerce/magento-product/components/ProductPagePrice/ProductPagePrice */
import { ProductPagePrice as ProductPagePriceBundleProductPagePrice } from '@graphcommerce/magento-product-bundle/plugins/BundleProductPagePrice'
import { ProductPagePrice as ProductPagePriceConfigurableProductPagePrice } from '@graphcommerce/magento-product-configurable/plugins/ConfigurableProductPage/ConfigurableProductPagePrice'
import { ProductPagePrice as ProductPagePriceDownloadableProductPagePrice } from '@graphcommerce/magento-product-downloadable/plugins/DownloadableProductPagePrice'
import type { DistributedOmit as OmitPrev } from 'type-fest'
import { ProductPagePrice as ProductPagePriceOriginal } from './ProductPagePrice.original'

// Re-export everything from the original file except the intercepted exports
export * from './ProductPagePrice.original'

type ProductPagePriceConfigurableProductPagePriceProps = OmitPrev<
  React.ComponentProps<typeof ProductPagePriceConfigurableProductPagePrice>,
  'Prev'
>

const ProductPagePriceConfigurableProductPagePriceInterceptor = (
  props: ProductPagePriceConfigurableProductPagePriceProps,
) => <ProductPagePriceConfigurableProductPagePrice {...props} Prev={ProductPagePriceOriginal} />

type ProductPagePriceBundleProductPagePriceProps = OmitPrev<
  React.ComponentProps<typeof ProductPagePriceBundleProductPagePrice>,
  'Prev'
>

const ProductPagePriceBundleProductPagePriceInterceptor = (
  props: ProductPagePriceBundleProductPagePriceProps,
) => (
  <ProductPagePriceBundleProductPagePrice
    {...props}
    Prev={ProductPagePriceConfigurableProductPagePriceInterceptor}
  />
)

type ProductPagePriceDownloadableProductPagePriceProps = OmitPrev<
  React.ComponentProps<typeof ProductPagePriceDownloadableProductPagePrice>,
  'Prev'
>

const ProductPagePriceDownloadableProductPagePriceInterceptor = (
  props: ProductPagePriceDownloadableProductPagePriceProps,
) => (
  <ProductPagePriceDownloadableProductPagePrice
    {...props}
    Prev={ProductPagePriceBundleProductPagePriceInterceptor}
  />
)

/**
 * Here you see the 'interceptor' that is applying all the configured plugins.
 *
 * This file is NOT meant to be modified directly and is auto-generated if the plugins or the
 * original source changes.
 *
 * @see {@link file://./ProductPagePrice.tsx} for original source file
 * @see {ProductPagePriceConfigurableProductPagePrice} for source of applied plugin
 * @see {ProductPagePriceBundleProductPagePrice} for source of applied plugin
 * @see {ProductPagePriceDownloadableProductPagePrice} for source of applied plugin
 */
export const ProductPagePrice = ProductPagePriceDownloadableProductPagePriceInterceptor
