name: merge-main-to-canary
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  merge-main-to-canary:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Merge
        run: |
          git fetch --unshallow
          git checkout canary
          git pull
          git merge main -m "Auto-merge main back to canary"
          git push
