name: release
on:
  push:
    branches:
      - 'main'
      - 'canary'
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: the-guild-org/shared-config/setup@main
        name: setup env
        with:
          nodeVersion: 16
      - name: set version variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=date::$(date +"%B %d, %Y")"
      - name: maybe set canary
        if: ${{ github.ref == 'refs/heads/canary' }}
        run: yarn changeset pre enter next
      - name: maybe set release
        if: ${{ github.ref != 'refs/heads/canary' }}
        run: yarn changeset pre exit
      - name: release / pull_request
        id: changesets
        uses: dotansimha/changesets-action@v1.3.3
        with:
          publish: 'yarn release'
          commit: 'chore(release): update monorepo packages versions'
          title: 'Upcoming Release Changes (${{ github.ref }})'
          createGithubReleases: ${{ inputs.createGithubReleases }}
          githubReleaseName: ${{ inputs.githubReleaseName || steps.vars.outputs.date }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
